### ISSUE TITLE
DatabaseMirror not configurable

### ISSUE THREAD

**Issue by bergkatten** [edestecd/puppet-clamav#4]
Hi,

I'm testing this module and found that some parameters in freshclam.conf are not changing to values in Hiera. 
I tried this:

clamav::manage_clamd: true
clamav::manage_freshclam: true

clamav::clamd_options:
  MaxScanSize: 500M
  MaxFileSize: 150M
clamav::freshclam_options:
  LogTime: yes
  HTTPProxyServer: myproxy.proxy.com
  HTTPProxyPort: 80
  NotifyClamd: /etc/clamd.conf
  DatabaseMirror: clam.host1.mydomain.com
  DatabaseMirror: clam.host2.mydomain.com
# DatabaseMirror database.clamav.net

Would that be possible to have even multple lines configured dynamicaly as DatabaseMirror in hiera?

Br,
/Istvan

**Comment by edestecd** [comment]
Yes this is possible.  You need to use an array for multiple DatabaseMirrors.
In yaml arrays are indicated with -
This should do what you want:

``` yaml
clamav::freshclam_options:
  LogTime: yes
  HTTPProxyServer: myproxy.proxy.com
  HTTPProxyPort: 80
  NotifyClamd: /etc/clamd.conf
  DatabaseMirror:
  - clam.host1.mydomain.com
  - clam.host2.mydomain.com
```

I'm going to add this to the README example as well.
